// Code generated by mockery v2.46.3. DO NOT EDIT.

package repo_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TxRepo is an autogenerated mock type for the TxRepo type
type TxRepo struct {
	mock.Mock
}

// RunInTx provides a mock function with given fields: ctx, fn
func (_m *TxRepo) RunInTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTxRepo creates a new instance of TxRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxRepo {
	mock := &TxRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
